image: node

stages:
  - test
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

before_script:
  - yarn --frozen-lockfile --production=false || true # Don't blow up when 'yarn' doesn't exist

install:
  stage: test
  script:
    - echo 🐖
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - yarn test --coverage

lint:
  stage: test
  script:
    - yarn lint

types:
  stage: test
  script:
    - yarn types

madge:
  stage: test
  script:
    - yarn madge

staging:
  image: ruby
  stage: release
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY
  only:
    - develop

production:
  image: ruby
  stage: release
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
