// flow-typed signature: dade427c98d4576d7635b1d022a14a01
// flow-typed version: <<STUB>>/i18n-webpack-plugin_v^1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'i18n-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'i18n-webpack-plugin/dist/MakeLocalizeFunction' {
  declare module.exports: any;
}

declare module 'i18n-webpack-plugin/dist/MissingLocalizationError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'i18n-webpack-plugin/dist/cjs'>;
}
declare module 'i18n-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'i18n-webpack-plugin/dist/index'>;
}
declare module 'i18n-webpack-plugin/dist/MakeLocalizeFunction.js' {
  declare module.exports: $Exports<'i18n-webpack-plugin/dist/MakeLocalizeFunction'>;
}
declare module 'i18n-webpack-plugin/dist/MissingLocalizationError.js' {
  declare module.exports: $Exports<'i18n-webpack-plugin/dist/MissingLocalizationError'>;
}
