// flow-typed signature: be36d57157baa3c6fa798447a43a95c3
// flow-typed version: <<STUB>>/madge_v^3.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'madge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'madge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'madge/bin/cli' {
  declare module.exports: any;
}

declare module 'madge/lib/api' {
  declare module.exports: any;
}

declare module 'madge/lib/cyclic' {
  declare module.exports: any;
}

declare module 'madge/lib/graph' {
  declare module.exports: any;
}

declare module 'madge/lib/log' {
  declare module.exports: any;
}

declare module 'madge/lib/output' {
  declare module.exports: any;
}

declare module 'madge/lib/tree' {
  declare module.exports: any;
}

declare module 'madge/test/amd' {
  declare module.exports: any;
}

declare module 'madge/test/amd/amdes6' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/a' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/b' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/c' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/d' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/e' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/f' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/g' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/h' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circular/main' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circularAlias/config' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circularAlias/dos' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circularAlias/x86' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circularRelative/a' {
  declare module.exports: any;
}

declare module 'madge/test/amd/circularRelative/foo/b' {
  declare module.exports: any;
}

declare module 'madge/test/amd/nested/a' {
  declare module.exports: any;
}

declare module 'madge/test/amd/nested/b' {
  declare module.exports: any;
}

declare module 'madge/test/amd/nested/main' {
  declare module.exports: any;
}

declare module 'madge/test/amd/ok/a' {
  declare module.exports: any;
}

declare module 'madge/test/amd/ok/d' {
  declare module.exports: any;
}

declare module 'madge/test/amd/ok/e' {
  declare module.exports: any;
}

declare module 'madge/test/amd/ok/sub/b' {
  declare module.exports: any;
}

declare module 'madge/test/amd/ok/sub/c' {
  declare module.exports: any;
}

declare module 'madge/test/amd/plugin' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/a' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/config' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/vendor/baz' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/vendor/jquery-2.0.3' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/vendor/jquery.bar-1.0' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/vendor/jquery.foo-1.0' {
  declare module.exports: any;
}

declare module 'madge/test/amd/requirejs/vendor/quux' {
  declare module.exports: any;
}

declare module 'madge/test/api' {
  declare module.exports: any;
}

declare module 'madge/test/cjs' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/a' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/b' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/both' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/c' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/chained' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/circular/a' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/circular/b' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/circular/c' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/circular/d' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/circular/foo' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/core' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/error' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/missing' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/multibase/1/a' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/multibase/2/b' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/nested' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/node_modules/a' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/node_modules/b' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/node_modules/c' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/node_modules/doom' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/node_modules/events2' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/node_modules/y' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/normal/a' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/normal/d' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/normal/sub/b' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/normal/sub/c' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/npm' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/strings' {
  declare module.exports: any;
}

declare module 'madge/test/cjs/word' {
  declare module.exports: any;
}

declare module 'madge/test/es6' {
  declare module.exports: any;
}

declare module 'madge/test/es6/absolute' {
  declare module.exports: any;
}

declare module 'madge/test/es6/absolute/a' {
  declare module.exports: any;
}

declare module 'madge/test/es6/absolute/b' {
  declare module.exports: any;
}

declare module 'madge/test/es6/circular/a' {
  declare module.exports: any;
}

declare module 'madge/test/es6/circular/b' {
  declare module.exports: any;
}

declare module 'madge/test/es6/circular/c' {
  declare module.exports: any;
}

declare module 'madge/test/es6/error' {
  declare module.exports: any;
}

declare module 'madge/test/es6/re-export/a' {
  declare module.exports: any;
}

declare module 'madge/test/es6/re-export/b-default' {
  declare module.exports: any;
}

declare module 'madge/test/es6/re-export/b-named' {
  declare module.exports: any;
}

declare module 'madge/test/es6/re-export/b-star' {
  declare module.exports: any;
}

declare module 'madge/test/es6/re-export/c' {
  declare module.exports: any;
}

declare module 'madge/test/es6/webpack/src/sub/abs' {
  declare module.exports: any;
}

declare module 'madge/test/es6/webpack/src/sub/index' {
  declare module.exports: any;
}

declare module 'madge/test/es6/webpack/src/sub/rel' {
  declare module.exports: any;
}

declare module 'madge/test/es6/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'madge/test/es7' {
  declare module.exports: any;
}

declare module 'madge/test/es7/async' {
  declare module.exports: any;
}

declare module 'madge/test/es7/other' {
  declare module.exports: any;
}

declare module 'madge/test/flow' {
  declare module.exports: any;
}

declare module 'madge/test/flow/cjs/calc' {
  declare module.exports: any;
}

declare module 'madge/test/flow/cjs/math' {
  declare module.exports: any;
}

declare module 'madge/test/flow/es/calc' {
  declare module.exports: any;
}

declare module 'madge/test/flow/es/math' {
  declare module.exports: any;
}

declare module 'madge/test/jsx' {
  declare module.exports: any;
}

declare module 'madge/test/jsx/basic' {
  declare module.exports: any;
}

declare module 'madge/test/jsx/other' {
  declare module.exports: any;
}

declare module 'madge/test/typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'madge/bin/cli.js' {
  declare module.exports: $Exports<'madge/bin/cli'>;
}
declare module 'madge/lib/api.js' {
  declare module.exports: $Exports<'madge/lib/api'>;
}
declare module 'madge/lib/cyclic.js' {
  declare module.exports: $Exports<'madge/lib/cyclic'>;
}
declare module 'madge/lib/graph.js' {
  declare module.exports: $Exports<'madge/lib/graph'>;
}
declare module 'madge/lib/log.js' {
  declare module.exports: $Exports<'madge/lib/log'>;
}
declare module 'madge/lib/output.js' {
  declare module.exports: $Exports<'madge/lib/output'>;
}
declare module 'madge/lib/tree.js' {
  declare module.exports: $Exports<'madge/lib/tree'>;
}
declare module 'madge/test/amd.js' {
  declare module.exports: $Exports<'madge/test/amd'>;
}
declare module 'madge/test/amd/amdes6.js' {
  declare module.exports: $Exports<'madge/test/amd/amdes6'>;
}
declare module 'madge/test/amd/circular/a.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/a'>;
}
declare module 'madge/test/amd/circular/b.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/b'>;
}
declare module 'madge/test/amd/circular/c.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/c'>;
}
declare module 'madge/test/amd/circular/d.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/d'>;
}
declare module 'madge/test/amd/circular/e.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/e'>;
}
declare module 'madge/test/amd/circular/f.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/f'>;
}
declare module 'madge/test/amd/circular/g.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/g'>;
}
declare module 'madge/test/amd/circular/h.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/h'>;
}
declare module 'madge/test/amd/circular/main.js' {
  declare module.exports: $Exports<'madge/test/amd/circular/main'>;
}
declare module 'madge/test/amd/circularAlias/config.js' {
  declare module.exports: $Exports<'madge/test/amd/circularAlias/config'>;
}
declare module 'madge/test/amd/circularAlias/dos.js' {
  declare module.exports: $Exports<'madge/test/amd/circularAlias/dos'>;
}
declare module 'madge/test/amd/circularAlias/x86.js' {
  declare module.exports: $Exports<'madge/test/amd/circularAlias/x86'>;
}
declare module 'madge/test/amd/circularRelative/a.js' {
  declare module.exports: $Exports<'madge/test/amd/circularRelative/a'>;
}
declare module 'madge/test/amd/circularRelative/foo/b.js' {
  declare module.exports: $Exports<'madge/test/amd/circularRelative/foo/b'>;
}
declare module 'madge/test/amd/nested/a.js' {
  declare module.exports: $Exports<'madge/test/amd/nested/a'>;
}
declare module 'madge/test/amd/nested/b.js' {
  declare module.exports: $Exports<'madge/test/amd/nested/b'>;
}
declare module 'madge/test/amd/nested/main.js' {
  declare module.exports: $Exports<'madge/test/amd/nested/main'>;
}
declare module 'madge/test/amd/ok/a.js' {
  declare module.exports: $Exports<'madge/test/amd/ok/a'>;
}
declare module 'madge/test/amd/ok/d.js' {
  declare module.exports: $Exports<'madge/test/amd/ok/d'>;
}
declare module 'madge/test/amd/ok/e.js' {
  declare module.exports: $Exports<'madge/test/amd/ok/e'>;
}
declare module 'madge/test/amd/ok/sub/b.js' {
  declare module.exports: $Exports<'madge/test/amd/ok/sub/b'>;
}
declare module 'madge/test/amd/ok/sub/c.js' {
  declare module.exports: $Exports<'madge/test/amd/ok/sub/c'>;
}
declare module 'madge/test/amd/plugin.js' {
  declare module.exports: $Exports<'madge/test/amd/plugin'>;
}
declare module 'madge/test/amd/requirejs/a.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/a'>;
}
declare module 'madge/test/amd/requirejs/config.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/config'>;
}
declare module 'madge/test/amd/requirejs/vendor/baz.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/vendor/baz'>;
}
declare module 'madge/test/amd/requirejs/vendor/jquery-2.0.3.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/vendor/jquery-2.0.3'>;
}
declare module 'madge/test/amd/requirejs/vendor/jquery.bar-1.0.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/vendor/jquery.bar-1.0'>;
}
declare module 'madge/test/amd/requirejs/vendor/jquery.foo-1.0.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/vendor/jquery.foo-1.0'>;
}
declare module 'madge/test/amd/requirejs/vendor/quux.js' {
  declare module.exports: $Exports<'madge/test/amd/requirejs/vendor/quux'>;
}
declare module 'madge/test/api.js' {
  declare module.exports: $Exports<'madge/test/api'>;
}
declare module 'madge/test/cjs.js' {
  declare module.exports: $Exports<'madge/test/cjs'>;
}
declare module 'madge/test/cjs/a.js' {
  declare module.exports: $Exports<'madge/test/cjs/a'>;
}
declare module 'madge/test/cjs/b.js' {
  declare module.exports: $Exports<'madge/test/cjs/b'>;
}
declare module 'madge/test/cjs/both.js' {
  declare module.exports: $Exports<'madge/test/cjs/both'>;
}
declare module 'madge/test/cjs/c.js' {
  declare module.exports: $Exports<'madge/test/cjs/c'>;
}
declare module 'madge/test/cjs/chained.js' {
  declare module.exports: $Exports<'madge/test/cjs/chained'>;
}
declare module 'madge/test/cjs/circular/a.js' {
  declare module.exports: $Exports<'madge/test/cjs/circular/a'>;
}
declare module 'madge/test/cjs/circular/b.js' {
  declare module.exports: $Exports<'madge/test/cjs/circular/b'>;
}
declare module 'madge/test/cjs/circular/c.js' {
  declare module.exports: $Exports<'madge/test/cjs/circular/c'>;
}
declare module 'madge/test/cjs/circular/d.js' {
  declare module.exports: $Exports<'madge/test/cjs/circular/d'>;
}
declare module 'madge/test/cjs/circular/foo.js' {
  declare module.exports: $Exports<'madge/test/cjs/circular/foo'>;
}
declare module 'madge/test/cjs/core.js' {
  declare module.exports: $Exports<'madge/test/cjs/core'>;
}
declare module 'madge/test/cjs/error.js' {
  declare module.exports: $Exports<'madge/test/cjs/error'>;
}
declare module 'madge/test/cjs/missing.js' {
  declare module.exports: $Exports<'madge/test/cjs/missing'>;
}
declare module 'madge/test/cjs/multibase/1/a.js' {
  declare module.exports: $Exports<'madge/test/cjs/multibase/1/a'>;
}
declare module 'madge/test/cjs/multibase/2/b.js' {
  declare module.exports: $Exports<'madge/test/cjs/multibase/2/b'>;
}
declare module 'madge/test/cjs/nested.js' {
  declare module.exports: $Exports<'madge/test/cjs/nested'>;
}
declare module 'madge/test/cjs/node_modules/a.js' {
  declare module.exports: $Exports<'madge/test/cjs/node_modules/a'>;
}
declare module 'madge/test/cjs/node_modules/b.js' {
  declare module.exports: $Exports<'madge/test/cjs/node_modules/b'>;
}
declare module 'madge/test/cjs/node_modules/c.js' {
  declare module.exports: $Exports<'madge/test/cjs/node_modules/c'>;
}
declare module 'madge/test/cjs/node_modules/doom.js' {
  declare module.exports: $Exports<'madge/test/cjs/node_modules/doom'>;
}
declare module 'madge/test/cjs/node_modules/events2.js' {
  declare module.exports: $Exports<'madge/test/cjs/node_modules/events2'>;
}
declare module 'madge/test/cjs/node_modules/y.js' {
  declare module.exports: $Exports<'madge/test/cjs/node_modules/y'>;
}
declare module 'madge/test/cjs/normal/a.js' {
  declare module.exports: $Exports<'madge/test/cjs/normal/a'>;
}
declare module 'madge/test/cjs/normal/d.js' {
  declare module.exports: $Exports<'madge/test/cjs/normal/d'>;
}
declare module 'madge/test/cjs/normal/sub/b.js' {
  declare module.exports: $Exports<'madge/test/cjs/normal/sub/b'>;
}
declare module 'madge/test/cjs/normal/sub/c.js' {
  declare module.exports: $Exports<'madge/test/cjs/normal/sub/c'>;
}
declare module 'madge/test/cjs/npm.js' {
  declare module.exports: $Exports<'madge/test/cjs/npm'>;
}
declare module 'madge/test/cjs/strings.js' {
  declare module.exports: $Exports<'madge/test/cjs/strings'>;
}
declare module 'madge/test/cjs/word.js' {
  declare module.exports: $Exports<'madge/test/cjs/word'>;
}
declare module 'madge/test/es6.js' {
  declare module.exports: $Exports<'madge/test/es6'>;
}
declare module 'madge/test/es6/absolute.js' {
  declare module.exports: $Exports<'madge/test/es6/absolute'>;
}
declare module 'madge/test/es6/absolute/a.js' {
  declare module.exports: $Exports<'madge/test/es6/absolute/a'>;
}
declare module 'madge/test/es6/absolute/b.js' {
  declare module.exports: $Exports<'madge/test/es6/absolute/b'>;
}
declare module 'madge/test/es6/circular/a.js' {
  declare module.exports: $Exports<'madge/test/es6/circular/a'>;
}
declare module 'madge/test/es6/circular/b.js' {
  declare module.exports: $Exports<'madge/test/es6/circular/b'>;
}
declare module 'madge/test/es6/circular/c.js' {
  declare module.exports: $Exports<'madge/test/es6/circular/c'>;
}
declare module 'madge/test/es6/error.js' {
  declare module.exports: $Exports<'madge/test/es6/error'>;
}
declare module 'madge/test/es6/re-export/a.js' {
  declare module.exports: $Exports<'madge/test/es6/re-export/a'>;
}
declare module 'madge/test/es6/re-export/b-default.js' {
  declare module.exports: $Exports<'madge/test/es6/re-export/b-default'>;
}
declare module 'madge/test/es6/re-export/b-named.js' {
  declare module.exports: $Exports<'madge/test/es6/re-export/b-named'>;
}
declare module 'madge/test/es6/re-export/b-star.js' {
  declare module.exports: $Exports<'madge/test/es6/re-export/b-star'>;
}
declare module 'madge/test/es6/re-export/c.js' {
  declare module.exports: $Exports<'madge/test/es6/re-export/c'>;
}
declare module 'madge/test/es6/webpack/src/sub/abs.js' {
  declare module.exports: $Exports<'madge/test/es6/webpack/src/sub/abs'>;
}
declare module 'madge/test/es6/webpack/src/sub/index.js' {
  declare module.exports: $Exports<'madge/test/es6/webpack/src/sub/index'>;
}
declare module 'madge/test/es6/webpack/src/sub/rel.js' {
  declare module.exports: $Exports<'madge/test/es6/webpack/src/sub/rel'>;
}
declare module 'madge/test/es6/webpack/webpack.config.js' {
  declare module.exports: $Exports<'madge/test/es6/webpack/webpack.config'>;
}
declare module 'madge/test/es7.js' {
  declare module.exports: $Exports<'madge/test/es7'>;
}
declare module 'madge/test/es7/async.js' {
  declare module.exports: $Exports<'madge/test/es7/async'>;
}
declare module 'madge/test/es7/other.js' {
  declare module.exports: $Exports<'madge/test/es7/other'>;
}
declare module 'madge/test/flow.js' {
  declare module.exports: $Exports<'madge/test/flow'>;
}
declare module 'madge/test/flow/cjs/calc.js' {
  declare module.exports: $Exports<'madge/test/flow/cjs/calc'>;
}
declare module 'madge/test/flow/cjs/math.js' {
  declare module.exports: $Exports<'madge/test/flow/cjs/math'>;
}
declare module 'madge/test/flow/es/calc.js' {
  declare module.exports: $Exports<'madge/test/flow/es/calc'>;
}
declare module 'madge/test/flow/es/math.js' {
  declare module.exports: $Exports<'madge/test/flow/es/math'>;
}
declare module 'madge/test/jsx.js' {
  declare module.exports: $Exports<'madge/test/jsx'>;
}
declare module 'madge/test/jsx/basic.jsx' {
  declare module.exports: $Exports<'madge/test/jsx/basic'>;
}
declare module 'madge/test/jsx/other.jsx' {
  declare module.exports: $Exports<'madge/test/jsx/other'>;
}
declare module 'madge/test/typescript.js' {
  declare module.exports: $Exports<'madge/test/typescript'>;
}
