// flow-typed signature: 8e12779718bbe6e203b8a1eba9570083
// flow-typed version: <<STUB>>/reactizer-lib_v^0.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactizer-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactizer-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactizer-lib/lib/Day/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Day/index' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Num/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Num/index' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Price/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Price/index' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/services/intl/consts' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/services/intl/withIntl' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Text/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Text/index' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Time/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'reactizer-lib/lib/Time/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactizer-lib/lib/Day/__tests__/index.spec.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Day/__tests__/index.spec'>;
}
declare module 'reactizer-lib/lib/Day/index.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Day/index'>;
}
declare module 'reactizer-lib/lib/Num/__tests__/index.spec.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Num/__tests__/index.spec'>;
}
declare module 'reactizer-lib/lib/Num/index.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Num/index'>;
}
declare module 'reactizer-lib/lib/Price/__tests__/index.spec.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Price/__tests__/index.spec'>;
}
declare module 'reactizer-lib/lib/Price/index.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Price/index'>;
}
declare module 'reactizer-lib/lib/services/intl/consts.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/services/intl/consts'>;
}
declare module 'reactizer-lib/lib/services/intl/withIntl.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/services/intl/withIntl'>;
}
declare module 'reactizer-lib/lib/Text/__tests__/index.spec.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Text/__tests__/index.spec'>;
}
declare module 'reactizer-lib/lib/Text/index.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Text/index'>;
}
declare module 'reactizer-lib/lib/Time/__tests__/index.spec.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Time/__tests__/index.spec'>;
}
declare module 'reactizer-lib/lib/Time/index.js' {
  declare module.exports: $Exports<'reactizer-lib/lib/Time/index'>;
}
