// flow-typed signature: 09382bc04736e306d72dfd57ca625db9
// flow-typed version: <<STUB>>/@babel/preset-stage-2_v^7.0.0-beta.51/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-stage-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-stage-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-stage-2/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-stage-2/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-stage-2/lib/index'>;
}
